### ISSUE TITLE
Did not recognise RDF format object Turtle

### ISSUE THREAD

**Issue by stdob** [jbarrasa/neosemantics#1]
It's okay if load the data using the following query:

`CALL semantics.importRDF("https://raw.githubusercontent.com/jbarrasa/neosemantics/master/src/test/resources/jeu-de-donnees-des-jeux-de-donnees-open-data-paris.rdf","RDF/XML", false, 500)`

But get the error using the following query:

`CALL semantics.importRDF("https://raw.githubusercontent.com/jbarrasa/neosemantics/master/src/test/resources/opentox-example.ttl","Turtle", false, 500)`

`Failed to invoke procedure `semantics.importRDF`: Caused by: org.openrdf.rio.UnsupportedRDFormatException: Did not recognise RDF format object Turtle (mimeTypes=text/turtle, application/x-turtle; ext=ttl)`

_Neo4j, EE, 3.0.1_

**Comment by jbarrasa** [comment]
Hi, can you confirm you've included in the sesame-rio-turtle-4.1.1.jar in the plugins directory. There seem to be separate jars for each serialisation format. (sesame-rio-jsonld-4.1.1.jar, sesame-rio-ntriples-4.1.1.jar, sesame-rio-trig-4.1.1.jar, etc)
Let me know if this helps.

**Comment by stdob** [comment]
Yes, it helped. The problem was that I was trying to compile with `assembly-plugin` (jar-with-dependencies).
