### ISSUE TITLE
Fails to load RDF/XML

### ISSUE THREAD

**Issue by pinx** [jbarrasa/neosemantics#10]
I tried importing my own rdf, and the French food rdf. Both give the error message
`The required index on :Resource(uri) could not be found`
Attached part of the file, for testing (remove the .txt extension)
I used the statement:
`CALL semantics.importRDF("file:////home/marcel/Downloads/food.rdf" , "RDFXML", true, true , 9000)`
(with various combinations of true and false flags)
[food.rdf.txt](https://github.com/jbarrasa/neosemantics/files/620368/food.rdf.txt)

**Comment by jbarrasa** [comment]
Hi!
Before running the import procedure an index needs to be created on property uri of Resource nodes. 
You just need to run `CREATE INDEX ON :Resource(uri)` on your Neo4j DB. 
Full description here: https://jesusbarrasa.wordpress.com/2016/06/07/importing-rdf-data-into-neo4j/

Cheers,


JB.
