### ISSUE TITLE
Some procedures are hidden in readme

### ISSUE THREAD

**Issue by palandlom** [jbarrasa/neosemantics#103]
When I get list of all semantic.* procedures by:
```
CALL dbms.procedures() YIELD name,signature,description
WHERE name =~ "seman.*"
RETURN name,signature,description
```
... I discovered that there are some interesting ones (dealing with inference) like:

```
semantics.inference.nodesInCategory
semantics.inference.nodesLabelled
```
but why they are not present in project readme (they are beta, just-for-fun or something else)? Can I use them for production?

**Comment by jbarrasa** [comment]
;-)
Working on the documentation at the moment. I hope I'll publish it in the next few days. 
If you want to know more you can have a look at the unit tests.

Cheers,

JB.

**Comment by palandlom** [comment]
OK we will wait)
