### ISSUE TITLE
i don't know how to use neosemantics，could you please tell me？

### ISSUE THREAD

**Issue by gyfbaym** [jbarrasa/neosemantics#107]
i have downloaded it，and copy it in plugin，and then i don't know how to import rdf data into neo4j

**Comment by jbarrasa** [comment]
Hi @gyfbaym , all you need to do is restart your Neo4j DB, open the browser and try any of the stored procedures described in the [README](https://github.com/jbarrasa/neosemantics/blob/3.5/README.md).
For example: 
`CALL semantics.importRDF("file:///.../yourTurtleFile.ttl","Turtle") `

If you need some ideas, you can have a look at [these blog posts](https://jbarrasa.com/category/graph-rdf/).

I hope this helps.

**Comment by jbarrasa** [comment]
We've now also released a complete manual. You can take a look [here](http://jbarrasa.github.io/neosemantics/).
