### ISSUE TITLE
Unable to Execute RDF Export Cypher Statement Through Neo4j Python Drivers

### ISSUE THREAD

**Issue by ankurgakhar** [jbarrasa/neosemantics#117]
Hi Jesus,

Warm Greetings!

First, thanks for providing the wonderful tool i.e. Neosemantics, along with a well-written documentation of it. It has really made the task of working with RDF & Neo4j fun and easy!

I have a requirement to access Neo4j from python, and for it i am using Py2Neo Driver for Python. I am facing challenge while running any of the :GET & :POST queries related to RDF using the python driver(I also tried the official Neo4j Driver i.e. Neo4j Bolt but the problem persists). 

The error i am getting is 'Syntax Error: Invalid Input' on the use of ":" as the starting character of the command. Here is a sample Cypher command mentioned in the user guide, for reference.
**:POST /rdf/cypher
{ "cypher" : "MATCH path = (n:Customer { customerID : 'GROSR'})-[:PURCHASED]->(o)-[:ORDERS]->()-[:PART_OF]->(:Category { categoryName : 'Beverages'}) RETURN path " , "format": "RDF/XML" }**

The above command works absolutely fine in Neo4j Browser but while executing the same command via python driver I am facing error. 

Can you please have a look at it at your end and share your insights.

**Comment by jbarrasa** [comment]
Hi @ankurgakhar, glad to hear you're finding NSMNTX useful.
The `:POST` syntax in the Neo4j browser is just a shortcut for a standard HTTP POST request. In python you can use [the requests library](https://2.python-requests.org/en/master/) for that. Here's an example. I also use [the rdflib library](https://rdflib.readthedocs.io/en/stable/gettingstarted.html) to consume the RDF produced by Neo4j+NSMNTX:

```
import requests
import json
import rdflib

url = 'http://localhost:7474/rdf/cypher'

cypher = 'MATCH path = (cust:Customer)-[:PURCHASED]->(o)-[:ORDERS]->()-[:PART_OF]->(cat:Category) \
		  WHERE cust.customerID = "GROSR" AND cat.categoryName = "Beverages" \
		  RETURN path '

payload = { 'cypher' : cypher , 'format' : 'RDF/XML' }

response = requests.post(url, auth=('neo4j', 'neo'), data = json.dumps(payload))
response.raise_for_status()  # raise an error on unsuccessful status codes

g=rdflib.Graph()
g.parse(data=response.text)

for s,p,o in g:
    print s,p,o
```

Hope this helps.

JB.

**Comment by ankurgakhar** [comment]
Hi JB, 

Thanks for the time and sharing the solution. It really works!!
