### ISSUE TITLE
semantics.getLangValue with multiple elements with the same language

### ISSUE THREAD

**Issue by eetuko** [jbarrasa/neosemantics#119]
If a given property is composed of multiple strings in the same language, only one is retained. 

For example, analyzing ESCO skills, one can have many synonyms for a given skill in a single skill.

It would be useful to be able to return an array with all the elements in the specified language.

Is there any workaround in the mean time?

Thanks.

**Comment by jbarrasa** [comment]
Thanks for your interest in NSMNTX, @eetuko !

That's not the case since 3.5.0.1. What version of NSMNTX are you using?

By combining the config params: **keepLangTag**, **handleMultival** and **multivalPropList** you can specify which properties are multivalued, and whether to keep all values or not (and also whether to keep lang tags). 

There's [an example](http://jbarrasa.github.io/neosemantics/#_handling_language_tags) in the manual.  Have a look and let me know if that solves your problem.

JB.

**Comment by eetuko** [comment]
Thanks for the quick reply. I was probably not clear enough. I do use the params you mention during the import. My point is, say for a node n, you have a property which is:

> skos__altLabel: bezpieczne zarządzanie produktami leczniczymi@pl,métodos de administración de medicamentos@es,methods and principles of managing medicine@en,methods and principles of storing medicines**@en**,veilig beheer van medicatie@nl,veilig beheer van medicijnen@nl,medication safety**@en**,safe management of medicine**@en**,medicine management methods@en,métodos y principios de conservación de medicamentos@es

As you can see, I highlighted multiple skills that are in english.

If you apply semantics.getLangValue("en",  n.skos__altLabel), you would get in return only the first expression in english which is "methods and principles of managing medicine" and not an array with the three one.

By the way thanks for the good work on the manual, I just started to use NSMNTX a day ago and its working very well :-)

**Comment by jbarrasa** [comment]
Ah, I get it, you're right, the function returns only the first match for a given language tag... 
Here's a cypher workaround. 

I'll load this dataset for this example:
```
call semantics.importRDFSnippet('@prefix show: <http://example.org/vocab/show/> .
@prefix ind: <http://example.org/ind/> .

ind:218 a show:TVSeries .
ind:218 show:name "That Seventies Show" .
ind:218 show:localName "That Seventies Show"@en .                 
ind:218 show:localName "Cette Série des Années Soixante-dix"@fr .
ind:218 show:localName "Un deuxieme titren en Francais"@fr .
ind:218 show:localName "Et meme un troisieme"@fr .
ind:218 show:localName "Cette Série des Années Septante"@fr-be . ', 'Turtle', { keepLangTag: true, handleMultival: 'ARRAY', multivalPropList : ['http://example.org/vocab/show/localName']})
```

This expresssion should return the result you expect:

```
MATCH (n:ns0__TVSeries) 
RETURN [str in n.ns0__localName where str ends with "@fr" | substring(str,0,length(str)-3)] as frenchValues
```

in this example, here's the output:

```
╒══════════════════════════════════════════════════════════════════════╕
│"frenchValues"                                                        │
╞══════════════════════════════════════════════════════════════════════╡
│["Cette Série des Années Soixante-dix","Un deuxieme titren en Francais│
│","Et meme un troisieme"]                                             │
└──────────────────────────────────────────────────────────────────────┘
```

Glad to hear your experience with NSMNTX is being positive. Looking forward to hearing more on your projects with Neo4j+NSMNTX.

**Comment by eetuko** [comment]
Nice thank you very much.

On your example, I had something like:
```
MATCH (n:ns0__TVSeries)
RETURN [x in n.ns0__localName WHERE semantics.getLangValue("fr",x) is not NULL | semantics.getLangValue("fr",x)] as frenchValues
```

As my CYPHER is not back to speed yet.
It's exploratory for now, many thanks for the support !
