### ISSUE TITLE
Plans to move to 3.1 running with apoc?

### ISSUE THREAD

**Issue by mfkilgore** [jbarrasa/neosemantics#12]
I have been migrating to 3.1 checking your plans one.  Thanks

**Comment by jbarrasa** [comment]
Hi Michael, thanks for your message. Yes absolutely. I only need to find the time but I hope it will happen in the next few weeks.

But contributions are also welcome ;-)

Cheers,

JB.

**Comment by mfkilgore** [comment]
Sorry for the late reply, I have been out of the office…

I did a quick update to run in 3.1 locally but not sure if this is the way you want to move forward.  The changes I made were mostly in the POM (attached) to include new jar files and in the test code where there is a new process for loading resolving dependencies now that we have user defined functions.  I copied a utility class from apoc (Michael H), TestUtil and changed the code - ((GraphDatabaseAPI)db).getDependencyResolver().resolveDependency(Procedures.class).register(RDFImport.class);  to TestUtil.registerProcedure(db, RDFImport.class);

Works great in 3.1 I loaded a very large ontology with no problem at all using all of the call procedures.  

There is an issue with the restful interface returning error because it is not in a transaction.  This shows up in the RDFEndpointTest/testGetNodeById().  I have not had a chance to debug fully but in this test, on the second time through (doneOnce = true), when we try to process a relationship is when we see the not in transaction error.  

As I said incomplete but a start…

Talk to you soon,
____________________________________
Michael Kilgore
InfoClear Consulting
www.infoclearonline.com <http://www.infoclearonline.com/>
425.306.6042
Skype:mfkilgore

**Comment by mfkilgore** [comment]
Very nice, I was going to work on a PR and complete the above, but I see it has been done and a PR submitted.

**Comment by jbarrasa** [comment]
Hi, thanks a lot Michael, and sorry for the late reaction on my side.
I've accepted the pull request and fixed a couple of things that were preventing it from starting on 3.1.1 but it should be fine now.
Let me know if it works fine for you.

Cheers,

JB.

**Comment by mfkilgore** [comment]
Thanks for the update, I had a version working too, but will check out hour latest.
____________________________________
Michael Kilgore
InfoClear Consulting
www.infoclearonline.com <http://www.infoclearonline.com/>
425.306.6042
Skype:mfkilgore

**Comment by mfkilgore** [comment]
Just checked out the latest, everything works as expected.  Thanks again.
