### ISSUE TITLE
plugin does not install and work 

### ISSUE THREAD

**Issue by seungsoo-lee** [jbarrasa/neosemantics#22]
![image](https://cloud.githubusercontent.com/assets/7541723/24451124/83ab9cec-14b8-11e7-96ec-98b3d2d047b5.png)

I have built neosemantics from the git successfully.

But, when I move the .jar file to neo4j-community-3.1.3/plugin and modified the config file (config/neo4j.conf) as you mentioned, and then start neo4j,

I got above log information and neo4j failed.

**Comment by mfkilgore** [comment]
@seungsoo-lee I believe the issue is the version of apoc (https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases) currently included is not valid for 3.1.2 or 3.1.3.  Could you try updating the version of apoc to the latest release 3.1.2.5 and rebuild.  Also as apoc is included in this jar you can not also have it loaded in the neo4j plugins.

**Comment by B3DS-D01** [comment]
Hi @mfkilgore I have similar issue adding the plugin with 3.1.3 version of Neo. Trying to resolve from many hours now. Do you mean to update the pom.xml and build the package again?

**Comment by mfkilgore** [comment]
Yes update the POM to reference a later version of apoc and rebuild the jar.  Let me know if that works for you.  Has worked for me.

**Comment by B3DS-D01** [comment]
Yes it did work. I just did it.  However I see a warning as below

WARN  The following warnings have been detected with resource and/or provider classes:
WARNING: A HTTP GET method, public javax.ws.rs.core.Response semantics.extension.RDFEndpoint.exportOnto(org.neo4j.graphdb.GraphDatabaseService,java.lang.String), should not consume any entity.
  WARNING: A sub-resource method, public javax.ws.rs.core.Response semantics.extension.SemanticsSCOExpansionEndpoint.semanticypher(org.neo4j.graphdb.GraphDatabaseService,java.lang.String), with URI template, "/", is treated as a resource method

I hope I can ignore this or let me know if there is some configuration issue.

Thanks and regards
Azhar

**Comment by mfkilgore** [comment]
@B3DS-D01 which version of neo4j are you using.  There is and issue with .exe (windows) and .dmg (mac) versions and a conflict with the restful call interface warned about.  Installing the zip/tar versions of 3.1.3 should work better.

**Comment by seungsoo-lee** [comment]
Hi @mfkilgore, in my case, I downloaded pre-build version of neo4j-3.1.3 and unzip it.

So, I don't have pom.xml as shown in this picture.

![image](https://cloud.githubusercontent.com/assets/7541723/24536063/f8a55ffa-1612-11e7-9d10-9c5077d2c0fe.png)

what can I do?

**Comment by seungsoo-lee** [comment]
Hi @mfkilgore , I put apoc 3.1.2.5. jar file into [neo4j]/lib folder, and modified the config/neo4j.conf.

Then, It seems work properly, (checked call dbms.procedures())

But, I got the WARN msg as follows;

![image](https://cloud.githubusercontent.com/assets/7541723/24536278/5966839a-1614-11e7-8312-dfaed525ebec.png)

is it okay?

**Comment by moissinac** [comment]
Is it possible to get directly the jar for that release?

**Comment by saumier** [comment]
I have the same problem:
Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@7572ee61' was successfully initialized, but failed to start.

I am running Neo4j Community 3.2.5.  I compiled the latest version of the plugin with Maven 3.5.  The neosemantics-1.0-SNAPSHOT is the ONLY plugin in the plugins directory.  I am on High Sierra. 

Any ideas?

**Comment by jbarrasa** [comment]
Hi Gregory, 

Is that the only info in the logs? have you checked if there's anything else that could give us more clues on what's failing?

Did you install Neo4j community from a .dmg or did you download the tar? I've not tried the .dmg installer but based on this [coment](https://github.com/jbarrasa/neosemantics/issues/22#issuecomment-290239221) suggests that you may need to go with the tar if you haven't.

Finally, is it worth a try with [the pre-built jar](https://github.com/jbarrasa/neosemantics/releases) to check if you get the same behaviour? It would be a way of ruling out build problems.

Let me know.

Cheers,

JB.

**Comment by saumier** [comment]
Thanks for the tips.  I reinstalled neo4j from the tar (3.2.6), and your plugin worked like a charm with the pre-built jar. Super!

**Comment by jbarrasa** [comment]
Happy to hear.
There is a 3.3 release available now in case you want to move to Neo4j 3.3
Cheers,

JB.
