### ISSUE TITLE
plugin does not import ttl file

### ISSUE THREAD

**Issue by seungsoo-lee** [jbarrasa/neosemantics#24]
I succeeded to install this plugin and checked it works correctly.

But, When I downloaded YAGO data (.ttl format) and then tried to import the file,

but, it cannot import it.

Some contents of the file as follows:

![image](https://cloud.githubusercontent.com/assets/7541723/24698372/59cdeeac-1a2b-11e7-8418-063afa6c6d72.png)

And, neosemantics shows as follows when i try to import it:

![image](https://cloud.githubusercontent.com/assets/7541723/24698400/715e2abe-1a2b-11e7-850e-412ff90e5d06.png)

**Comment by jbarrasa** [comment]
Hi seungsoo-lee, could you share the "yagoWordnetIds.ttl" file (or at least a portion of it sufficient to reproduce the behaviour that you are getting? 
Cheers,

JB.

**Comment by jbarrasa** [comment]
Hi again, I've noticed that the RDF syntax name you're using is not correct, try `Turtle` instead of `ttl`.
See all valid options in the readme of the repo: https://github.com/jbarrasa/neosemantics

Let me know if that solves the problem.

JB.
