### ISSUE TITLE
How to export Query Response in .rdf format from Neo?

### ISSUE THREAD

**Issue by Amit325** [jbarrasa/neosemantics#30]
Hi @jbarrasa ,

I want to export the query response in .rdf format. I have created few nodes and relations among them. Now I need to export the Match Query result in .rdf format. I have successfully installed neosemantics-3.2.0.1-beta.jar and have copied the `dbms.unmanaged_extension_classes=semantics.extension=/rdf ` in the neo4j.conf file at the bottom with `#` prefix (If I won't put the # prefix, it is unable to start the server). I restarted the server and ran the `call dbms.procedures()`  this query in neo. I could see the listed procedures in the result.

Now if I query the below statement, I gets the result, this result I want the export in rdf format.

> MATCH p=(n:Maths)-[r:HAS_TOPIC]->() RETURN p LIMIT 25

I tried running this query

> :POST /rdf/cypher/  "MATCH p=(n:Maths)-[r:HAS_TOPIC]->() RETURN p LIMIT 25"

I got this error `Payload does not seem to be valid (JSON) data`. Please help me on this. 

Thanks

**Comment by jbarrasa** [comment]
Hi, 
First of all, if you put a hash before the line in the config file, you are effectively making it a comment so it will be ignored. If by uncommenting it you get an error, you should find out what it is and fix it. 95% chances it will be a version compatibility issue. Make sure that you build neosemantics for the version of Neo4j you're using but if you want to take the easiest route, just download the jar from the releases section and use it on Neo4j 3.2.x

To check that the extension is installed, type `:GET /rdf/ping` in the browser and you should get a ping message back.

Finally, do not use path expressions as they probably won't return what you expect. There is no obvious equivalent of a Neo4j path in RDF but I'll write on this in the docs when I have a minute but it's a good point you've raised.

In your example try this instead. Same query but returning each individual item as opposed to the path.

`:POST /rdf/cypher "MATCH (n:Maths)-[r:HAS_TOPIC]->(x) RETURN * LIMIT 25" `

Let me know how it goes,

JB.

**Comment by jbarrasa** [comment]
Serialising paths returned by a cypher query as RDF is tracked on #33
