### ISSUE TITLE
About dealing with an exception

### ISSUE THREAD

**Issue by TheIllsionist** [jbarrasa/neosemantics#32]
When I invoke the procedure 'semantics.importRDF' it reports:
 org.neo4j.driver.v1.exceptions.ClientException: Failed to invoke procedure `semantics.importRDF`: Caused by: org.openrdf.rio.UnsupportedRDFormatException: Did not recognise RDF format object Turtle (mimeTypes=text/turtle, application/x-turtle; ext=ttl)

**Comment by TheIllsionist** [comment]
I have changed a little bit about the code,but I didn't change anything about the interface of the code,why does this happen and how to deal with it?

**Comment by jbarrasa** [comment]
Hi,

I'm afraid I'm going to need some more info to try and help you.

Can you send the complete invocation `semantics.importRDF(...)` and the source RDF file you're trying to load (or at least a sample of it).

Also when you say you've changed the code you mean you've branched the source modified and compiled your own jar? If that is the case I'd need the source too ;-)

Cheers,

JB.

**Comment by TheIllsionist** [comment]
I didn't create a new branch.I just download the source code,create a new maven project,copy the pom.xml and the source code to my new project,and then change some code,and then package it.Here are a list about my change,after that I'll show you my code:
    1.I changed the 'languageFilter' so that it can filter more than one languages;
    2.My purpose of using this procedure is to import Freebase into the community edition of neo4j,so I change something about the namespace mapping on the creatation of prefix;
    3.I also changed the 'shorten' concept so that it can 'shorten' both of the sub,obj and pre of a triple;
    4.According to the freebase data dump,I add the freebase's type concept as Label for nodes;
    5.For multivalued properties,I don't overwrite it but store it using ';' as values' seperator;
    By the way,I'm chinese and I hope you can understand my pool English's meaning.....


   When I invoke the procedure I use:
       call semantics.importRDF("file:///home/xhx/freebase/freebase_0000","Turtle",
       {shortenUrls:true,typeToLabels:true,languageFilter:['en','zh']})


   I only changed the RDFImport.java and DirectStatementLoader.java with the procedures no parameter and their data type has been changed.Here are the files:
[DirectStatementLoader.txt](https://github.com/jbarrasa/neosemantics/files/1179767/DirectStatementLoader.txt)
[RDFImport.txt](https://github.com/jbarrasa/neosemantics/files/1179766/RDFImport.txt)
[pom.txt](https://github.com/jbarrasa/neosemantics/files/1179770/pom.txt)
 Just change the file's suffix you can get the original file.
  If you still have question,just ask me.I will be very thankful if you can help me.

**Comment by TheIllsionist** [comment]
I cut the freebase data dump into 1044 pieces,and here is one of them,it is a little large:


[freebase_00000.txt](https://github.com/jbarrasa/neosemantics/files/1179778/freebase_00000.txt)
The original file name is 'freebase_0000' without the '.txt' suffix.

**Comment by TheIllsionist** [comment]
I cut the freebase data dump into 1044 pieces,and here is one of them,Here are a sample:
[freebase_00000.txt](https://github.com/jbarrasa/neosemantics/files/1179780/freebase_00000.txt)



The original file name is 'freebase_0000' without the '.txt' suffix.

**Comment by TheIllsionist** [comment]
I'll be left about 20 minutes  for dinner, waiting for your reply ,thank you!

**Comment by jbarrasa** [comment]
Hi, can you post the full stack trace?
Check in the neo4j.log for the details of the UnsupportedRDFormatException

**Comment by TheIllsionist** [comment]
just wait for a moment...

**Comment by TheIllsionist** [comment]
I found a new problem in my project,I have to know the edition of the maven-shade-plugin that you use when you package the JAR....

**Comment by TheIllsionist** [comment]
I am now trying another time.....

**Comment by jbarrasa** [comment]
Yes, it looks like a build issue.
Make sure you bundle in the jar all the different dependencies for all the RDF serialization formats (RDFXML, Turtle, NTriples, etc.)
Let me know how it goes.

**Comment by jbarrasa** [comment]
BTW, this Idea of extending the language filter to a list of values to enable multi-language filter sounds interesting, if you want to create a PR, I'd be happy to include it.

**Comment by TheIllsionist** [comment]
Ok,I will fix the build problem first,after that I will create a PR.

**Comment by TheIllsionist** [comment]
Yes!!! It is a build problem,I just fixed it!!Thank you for your help!!

**Comment by jbarrasa** [comment]
Glad to hear. 
Enjoy.

JB.
