### ISSUE TITLE
Display issue in neo4j-browser for RDF imported with shortenUrls:false

### ISSUE THREAD

**Issue by lifan0127** [jbarrasa/neosemantics#35]
When RDF was imported with full URI's as node labels, the node representation could not be properly customized in neo4j browser.

To reproduce, import the following ontology:

```
CALL semantics.importRDF("https://protege.stanford.edu/ontologies/pizza/pizza.owl","RDF/XML", { shortenUrls: false, typesToLabels: true, commitSize: 9000 })
```
and then run the following cypher query:

```
MATCH p=()-[r:`http://www.w3.org/2000/01/rdf-schema#subClassOf`]->() RETURN p LIMIT 25
```

All the nodes were in default grey color. From the UI, changing node color for `http://www.w3.org/2002/07/owl#Class` or `http://www.w3.org/2002/07/owl#Class` had no effect. It was also not possible to choose `uri` as node caption. The nodes could be colorized by using a graphstyle.grass file, but the color did not match the specification in grass.

![image](https://user-images.githubusercontent.com/7218193/32991790-30abd910-cd10-11e7-8901-a790069df95e.png)

None of the problems is present when shortenUrls is enabled.

Version: Neo4j-Community-3.2.7

**Comment by mdw00d** [comment]
It seems that if one does not specify shortenUrls:true and if typesToLabels is true, then the resultant graph will syntactically invalid label names --- the [Cypher documentation](https://neo4j.com/docs/cypher-manual/current/syntax/naming/) in Section 2.2.1 states that node labels cannot include special characters, which of course will be present in a URL.

**Comment by jbarrasa** [comment]
URIs are valid label, property and relationship identifiers so I don't think that's the problem. Both shortening with namespace prefixes or keeping the full uri should work without issues. 
I've not been able to try it on 3.2.7 but it seems to work fine on 3.5. See capture:
![image](https://user-images.githubusercontent.com/9989143/56733567-6b825f80-6758-11e9-9971-21ae29b6bd32.png)
Also, note the triangle at the bottom right of your screen capture. If you click on it the list of available properties for a given label is displayed, which seems to work fine with urls as my screen capture shows.
I'll close the issue for now but feel free to reopen if you disagree.
