### ISSUE TITLE
Only [semantics.runConsistencyChecks] available as procedure

### ISSUE THREAD

**Issue by nick-bt** [jbarrasa/neosemantics#4]
I'm experimenting with importing an RDF file in to a local Neo4J instance using your tools, but for some reason when I build the jar and add to Neo4J the only procedure available is [semantics.runConsistencyChecks]

I'm using maven to build the package - am I missing a command?  I'm a bit lost and would love to play around with your plugin.

**Comment by JeromeBaton** [comment]
@nick-bt I saw somewhere on this site that you need to put the dependency jars in $NEO/plugins as well.
Then I face a stream+generics error

**Comment by wadael** [comment]
@nick-bt See the PR by @samuraraujo

**Comment by jbarrasa** [comment]
I've accepted @samuraraujo's PR and checked in a significant number of changes. 
Could you please retry and confirm if the problem persists?
Thanks!

JB.

**Comment by nick-bt** [comment]
I can build the file now - no issues.  You've added another param to importRDF
that isn't in the readme so perhaps update that.
I'm getting errors using the plugin now, but I haven't tried enough to know
whether it's my RDF file, or something else.  I'll keep at it for now.
Thanks for the changes.
-Nick
 





On Sun, Nov 13, 2016 7:44 PM, J. Barrasa notifications@github.com
wrote:
I've accepted @samuraraujo's PR and checked in a significant number of changes. 
Could you please retry and confirm if the problem persists?
Thanks!

JB.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



Nick DymentDirector of Business Development and Operationswww.bigterminal.com
9057260919  ||nick@bigterminal.com

**Comment by wadael** [comment]
Code builds. Used the fat jar that embeds Apoc
Five semantics.* procedures appear as result of CALL dbms.procedures()

**Comment by nick-bt** [comment]
I got that working too.  The preview and import RDF files aren't working for
sample files I'm using, including the link from your wiki -
http://fr.openfoodfacts.org/data/fr.openfoodfacts.org.products.rdf

sample query:
CALL
semantics.importRDF("http://fr.openfoodfacts.org/data/fr.openfoodfacts.org.products.rdf","RDF/XML",
true, false, 25000)
 





On Mon, Nov 14, 2016 11:15 AM, Jerome notifications@github.com
wrote:
Code builds. Used the fat jar that embeds Apoc
Five semantics.* procedures appear as result of CALL dbms.procedures()

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



Nick DymentDirector of Business Development and Operationswww.bigterminal.com
9057260919  ||nick@bigterminal.com

**Comment by wadael** [comment]
Import fails for me.
feedback is 



╒═════════════════╤═════════════╤══════════════════════════════╤══════════════════════════════╕
│terminationStatus│triplesLoaded│namespaces                    │extraInfo                     │
╞═════════════════╪═════════════╪══════════════════════════════╪══════════════════════════════╡
│KO               │75000        │{http://purl.org/dc/terms/: ns│Un caractère XML non valide (U│
│                 │             │0, http://www.w3.org/1999/02/2│nicode : 0x3) a été détecté da│
│                 │             │2-rdf-syntax-ns#: ns2, http://│ns le contenu d'élément du doc│
│                 │             │data.lirmm.fr/ontologies/food#│ument. [line 134210, column 85│
│                 │             │: ns1, http://xmlns.com/foaf/0│0]                            │
│                 │             │.1/: ns4, http://rdfs.org/ns/v│                              │
│                 │             │oid#: ns3}                    │                              │
└─────────────────┴─────────────┴──────────────────────────────┴──────────────────────────────┘

**Comment by wadael** [comment]
in EN:   An invalid XML character has been detected (Unicode : 0x3) in the content of the document [line 134210, column 850]

**Comment by wadael** [comment]
Found a random RDF file on the net. No issue

CALL semantics.importRDF("http://www.w3.org/2004/08/TalkFiles/2005/Talks.rdf","RDF/XML",true, false, 5000)

**Comment by jbarrasa** [comment]
Yep, just checked and the current version of the file contains some invalid characters. Older versions  of the RDF dump did not include them. 
This is an XML parsing error, so I'm afraid there is not much I can do as I am several layers up.
I use org.openrdf.rio but I'd be curious to see if this file can be even parsed by any XML library.
(See similar error parsing xml: http://stackoverflow.com/questions/5742543/an-invalid-xml-character-unicode-0xc-was-found).
Probably the best would be to drop a line to the OpenfoodFacts guys and ask them to fix it because they are producing a file that cannot be parsed.
Cheers,
JB.
