### ISSUE TITLE
 java.lang.ClassNotFoundException: org.neo4j.graphdb.mockfs.EphemeralFileSystemAbstraction

### ISSUE THREAD

**Issue by ghost** [jbarrasa/neosemantics#40]
Hello, I downloaded a lot of jars, but the program is running in the wrong way. Can you upload all the dependent jars? My version of neo4j is 3.3.1. error as follows:

 java.lang.ClassNotFoundException: org.neo4j.graphdb.mockfs.EphemeralFileSystemAbstraction

**Comment by jbarrasa** [comment]
Hi coolcatdog, you won't need any additional jar to make it work if you use the prebuilt one in the [releases section](https://github.com/jbarrasa/neosemantics/releases). What os are you running Neo4j on?
In any case, if you follow the instructions in the [README](https://github.com/jbarrasa/neosemantics/blob/3.3/README.md) you shold be fine.

**Comment by coolcatdog** [comment]
Hello, my system is windows, I have solved this problem, I downloaded a lot of jars from maven, thank you.
