### ISSUE TITLE
Could not parse JSONLD

### ISSUE THREAD

**Issue by axixueguia** [jbarrasa/neosemantics#42]
Hi,

I use your stored procedure to import a JSON/JSON-LD file into Neo4j. 
I get a error message: "Could not parse JSONLD"

However, I do check in the documentation that JSON-LD is supported by your tool.

How can I fix it please ?
Thanks in advance,
Best regards,

**Comment by jbarrasa** [comment]
Hi, 
Yes, JSON-LD is supported. 
Could you please let me know which version of Neo4j and neosemantics are you using? On what operating system? 
Also, is your json-ld dataset public? It would be useful to try and reproduce the problem.

Thanks.

JB.

**Comment by axixueguia** [comment]
Hi,
Thanks a lot for your prompt response. 

Since the error message was "Could not parse JSONLD", I though it was a compatibility issue after the update...
I use Neo4j 3.3.1 Community version. Unfortunately the JSON-LD dataset is not publicly available. 
I will run a rdf validator to see if there is any error in the file. 
I will give you a feedback when it's done.

Best regards

**Comment by jbarrasa** [comment]
If it's a parsing problem there will be some additional information in `logs/neo4j.log`.
I'd recommend you try first with a public dataset like the ones [in this repo](https://github.com/ariutta/json-ld-examples) just to make sure all is correctly installed.
Let me know how it goes.

JB.

**Comment by axixueguia** [comment]
Hi,
I checked logs/neo4j.log, there is no additional information.
Your program is correctly installed since tests with other datasets (rdf/xml) went well.
I run a rdf validator to the JSONLD file and it turns out that there are some consistency issues (data types) and opening tags. I think that explains the parsing problems...
I convert the JSONLD file into RDF format and corrected the issues in the file. It works now !

Thanks a lot for your help :-)
Best regards

**Comment by jbarrasa** [comment]
Great to hear.
It would be great if you could blog/tweet/etc... about your experience.

All the best.

JB.
