### ISSUE TITLE
How to Get Detailed Error?

### ISSUE THREAD

**Issue by JianChen123** [jbarrasa/neosemantics#43]
I tried to import our ontology serialized in Turtle format. It ended with KO terminationStatus with extraInfo "Users". I searched the code-base, extraInfo suppose to show exception message. But in this case, it only shows "Users". How can I get some hint to fix the issue?

**Comment by jbarrasa** [comment]
You mean the extra info shows the word "Users"?
This is quite strange.
Is there anything in the logs?
Hard to tell without more info. Is the RDF data you're trying to load public? If so, would you mind sharing so I can try to reproduce the problem.
Thanks!

**Comment by JianChen123** [comment]
Figured out. I missed one / in file path "file://Users/...". I guess the only word "Users" in extra info was referring to the root folder. Somehow the error message was cut off

**Comment by jbarrasa** [comment]
ok, thanks
