### ISSUE TITLE
problem running neosemantics plugin

### ISSUE THREAD

**Issue by nazarenkoartem** [jbarrasa/neosemantics#46]
Dear Developers,

 I am new at Neo4j, and I need to import RDF triples to Neo4j, as I've got from the description, mentioned plugin is devoted to this issue. 

**Reproduce steps:**

I followed all the steps: 
1. installed the .jar file, put into "plugin" folder;
2. added the line to conf (not commented);
3. stopped-started server; 
4. checked, if all procedures are added (success) 
5. checked if extension is mounted `:GET /rdf/ping ` (failed)
6. Then, if I try to: 
`CALL semantics.importRDF("file:///Users/Me/Downloads/opentox-example.turtle","Turtle", {shortenURLs: false, typesToLabels:true, commitSize:9000})`
I get:
"The required index on :Resource(uri) could not be found"

**Expected behavior**

The rdf triples from the document need to be displayed and the uri should be recognized.

**Current behavior**

Could not fetch URL: "Failed to fetch". This could be due to the remote server policy. See your web browsers error console for more information.

**System**

Windows8
Neo4j Desktop 1.0.14
Neo4j Browser version: 3.1.4

NB:
As I mentioned I am new to Neo4j and I would be grateful, if you can provide me with any help. Thank you in advance!

**Comment by mfkilgore** [comment]
I believe you are very close all you need to do is add the missing index - while not obvious the documentation says -


> Note that before running the import procedure an index needs to be created on property uri of Resource nodes. Just run CREATE INDEX ON :Resource(uri) on your Neo4j DB

**Comment by nazarenkoartem** [comment]
> I believe you are very close all you need to do is add the missing index - while not obvious the documentation says -

Thank you very much for your quick response. After `CREATE INDEX ON :Resource(uri) ` it worked well.

Using the chance, I would like to ask the following question:

When I am trying to  run:
`:GET /rdf/ping` or `:POST ....` it throws: 

Could not fetch URL: "Failed to fetch". This could be due to the remote server policy. See your web browsers error console for more information.

Something is wrong with HTTP methods, probably I missed again something.

Thank you again!

**Comment by mfkilgore** [comment]
Glad that worked for you.  On the next question double check that you have added the following to your neo4j.conf file - 

dbms.unmanaged_extension_classes=semantics.extension=/rdf
dbms.security.procedures.whitelist=semantics.*

**Comment by nazarenkoartem** [comment]
Sorry for the delay. Thank you very much for your help. Similar problem has already been considered in: 

[(https://github.com/neo4j/neo4j-browser/issues/687)]

I am not sure, that this is the appropriate place for asking questions, it is more for fixing bugs. I will appreciate, if you could provide me some information about groups or resources (such as stackoverflow), where I can ask questions about common, usual difficulties (for me as beginner it will be a great help). Thank you in advance!
