### ISSUE TITLE
OpenPermID RDF import problem

### ISSUE THREAD

**Issue by ShabsRA** [jbarrasa/neosemantics#51]
Hi Jesus

I'm a newbie at graph database, and I was trying to follow the example presented in your [blog](https://jbarrasa.com/2018/02/01/neo4j-is-your-rdf-store-part-3-thomson-reuters-openpermid/) and I actually used a newer file available on Thomson Reuters OpenPermID. Here is the script I tried in Neo4j browser: 

`CALL semantics.importRDF("file:///C:/Users/u6069094/Downloads/OpenPermID-bulk-organization-20180506_071051.ntriples.gz","N-Triples", {})`

![image](https://user-images.githubusercontent.com/37694968/39968495-810761ba-56c5-11e8-8522-e878416572b6.png)
I even tried the http link for the file and it didn't work either, gave me the same error:

`CALL semantics.importRDF("https://permid.org/sfiles/bulkDownload/OpenPermID-bulk-organization-20180506_071051.ntriples.gz?access-token=9XcaOjVbGGV6jLTt5InFKF8usmh4Bu2f","N-Triples", {})`

I would be grateful if you could provide me with any help. 
Thanks in advance!

**Comment by jbarrasa** [comment]
Hi, thanks for your interest,
Are you trying to import a zipped file? I'm afraid the current version of neosemantics cannot do this. 
You'll have to unzip it first. Let me know if that solves the problem.

That said, being able to load directly from a zip sounds like a great feature request. 
I'll keep it in mind for future releases :)

JB.

**Comment by ShabsRA** [comment]
Hi Jesus, 
Thanks for the review, I extracted the file and that worked in this stage, The data dump contains around 31391174   triples now. I will carry on for the rest of steps and see what will happen :)

S.R
