### ISSUE TITLE
Which version of the Neo4j Desktop on win10 should I use？

### ISSUE THREAD

**Issue by cld378632668** [jbarrasa/neosemantics#54]
Which version of the Neo4j Desktop on win10 should I use？

**Comment by cld378632668** [comment]
so I just need to move the release-version jar to ne4j/plugins directory , not the【 two】 jars after building the source code ？

**Comment by jbarrasa** [comment]
That's correct. Only one. Normally the neosemantics-[...].jar because it includes all required third party libraries. See comment on this in the README.
