### ISSUE TITLE
Import is fine.  Export gives "UndefinedError: Payload does not seem to be valid (JSON) data"

### ISSUE THREAD

**Issue by BrainAnnex** [jbarrasa/neosemantics#57]
NEO4J: 3.4.6 Community version
neosemantics plugin: neosemantics-3.4.0.1.jar
OS: Win10

Hello!  Install went fine: I moved the downloaded file "neosemantics-3.4.0.1.jar" to the "plugins" folder of neo4j installation, and re-started the server.

During restart  ( `./neo4j console` , after navigating to the `bin` folder in the installation location, from the Windows Power Shell), the console said:

> INFO  Mounted unmanaged extension [semantics.extension] at [/rdf]
> 2018-09-05 23:43:32.250+0000 WARN  The following warnings have been detected with resource and/or provider classes:
>   WARNING: A HTTP GET method, public javax.ws.rs.core.Response semantics.extension.RDFEndpoint.exportOnto(org.neo4j.graphdb.GraphDatabaseService,java.lang.String), should not consume any entity.

The INFO part sounds good... unclear if the WARNING matters...

Inside the Neo4j Browser, all seemed good at first:

1) `:GET /rdf/ping`   replies  `{"ping":"here!"}`

2) `call dbms.procedures()` shows a long list of names, including "semantics.importRDF" and various other "semantics._XYZ_" procedures

3) Import of RDF seems perfect: 
`call semantics.previewRDF("https://raw.githubusercontent.com/motools/musicontology/master/examples/clapton_perf/clapton.n3","Turtle", {})`
as expected creates a graph that seems to match the RDF file available from that location

So far so good....... BUT the Cypher endpoint does NOT work :(

Here's a Cypher query that works - it returns a node:    `MATCH (n:Person {name:"Juls"}) RETURN n`

However, when I issue:  
`:POST /rdf/cypher "MATCH (n:Person {name:"Juls"}) RETURN n"`

I get: 

> UndefinedError
> UndefinedError: Payload does not seem to be valid (JSON) data

All my other attempts of obtaining RDF fail, too.  For example:

`:GET /rdf/describe/id?nodeid=35`

(where 35 is the ID of an actual node) gives:

> FetchURLError
> FetchURLError: Could not fetch URL: "500 Server Error". This could be due to the remote server policy. See your web browsers error console for more information.

Screen shots attached.
![neo4j semantic plugin bug1](https://user-images.githubusercontent.com/41893046/45129134-c8cc9080-b136-11e8-8610-8a147417fc52.png)
![neo4j semantic plugin bug2](https://user-images.githubusercontent.com/41893046/45129135-c9fdbd80-b136-11e8-80d5-c520fad51b7b.PNG)

The console is now giving many error messages (here's the first part):

> 2018-09-06 00:10:50.720+0000 INFO  mimetipe in request: */*
> 2018-09-06 00:10:50.720+0000 INFO  Unrecognized serialization in accept header param. Defaulting to JSON-LD serialization
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> 2018-09-06 00:10:50.727+0000 WARN  /rdf/describe/id com/fasterxml/jackson/databind/JsonMappingException
> java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonMappingException
>         at org.eclipse.rdf4j.rio.jsonld.JSONLDWriterFactory.getWriter(JSONLDWriterFactory.java:31)
>         at org.eclipse.rdf4j.rio.Rio.createWriter(Rio.java:137)
>         at semantics.extension.RDFEndpoint$4.write(RDFEndpoint.java:388)
>         at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
>         at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)

I'm attaching the `debug.log` file (trimmed to show everything from the restart on).

Your help will be appreciated; the company where I work is considering using Neo4j, but RDF export is absolutely needed.  THANKS!
[debug.log](https://github.com/jbarrasa/neosemantics/files/2355118/debug.log)

**Comment by BrainAnnex** [comment]
Addendum: I re-downloaded the semantic plugin, and re-tried it with the ENTERPRISE version of Neo4j this time (3.4.6).  IDENTICAL issues :(
(Also, no difference on whether I use Chrome or Firefox for the Neo4j Browser...)

**Comment by jbarrasa** [comment]
Hi BrainAnnex, thanks for trying out neosemantics.

**First error:** Try single quotes (or escape the double ones) in your cypher, otherwise it won't parse the whole query correctly. Something like this should work: 
`:POST /rdf/cypher "MATCH (n:Person {name:'Juls'}) RETURN n"`

**Second error:** Missing jackson library. I excluded one of the third party jars required to produce JSON/LD (jackson) from the neosemantics build because it clashed with the version that APOC uses. And because most Neo4j users have APOC installed, all works fine. I suspect you have not installed APOC. So quick fix would be to install APOC (you can download it from here: https://github.com/neo4j-contrib/neo4j-apoc-procedures). It's a very useful library of stored procs and functions but if for whatever reason you cannot or do not want to install it, let me know and we'll discuss alternatives.

Let me know if this helps.

JB.

**Comment by BrainAnnex** [comment]
ah, mystery solved, THANKS! 
Indeed, I had not yet installed the awesome APOC.  After I did, it's all good now :) 

Maybe from your point of view, APOC is more basic, while RDF is a more specialized need; but the company where I work must have RDF...  so, APOC was a "_maybe try later, if needed_" while the neosemantic module was a "_try now as a potential deal-breaker_."

So, you might want to add "**install APOC first**" to the installation instructions on the [https://github.com/jbarrasa/neosemantics](https://github.com/jbarrasa/neosemantics) page.  Armed with the hindsight, I did a search for "APOC" on that page, to see if I had missed it... but the term does not appear anywhere.

I notice that JSON-LD is being returned...   **Is it possible to request a different serialization from within the Neo4j browser?**  I notice that you mention having to do a _curl_ call to do that...

I tried a _curl_ call (using the curl built into the Windows 10 command line), but it complains about the lack of login credentials:

```
>curl http://localhost:7474/rdf/cypher

{
  "errors" : [ {
    "code" : "Neo.ClientError.Security.Unauthorized",
    "message" : "No authentication header supplied."
  } ]
}

```
On a more general note, I'm puzzled why RDF _import_ is done by means of stored procedures, while RDF _export_ requires GET/POST calls...

By the way, I read many of your helpful blog entries - they are great! :)

**Comment by jbarrasa** [comment]
Happy to hear you find the blog posts helpful. Thanks. I'll add a comment to the doc page on the dependency on APOC for JSON-LD.

I'm considering adding a Stored Proc version of the export methods, watch this space. What's your use case? Can you share how you're using neosemantics?

Regarding authentication, requests to Neo4j are authenticated, so you have to include your credentials in your request. You can do this as described [here](https://neo4j.com/docs/developer-manual/current/http-api/authentication/) or if you are in test mode, you can also disable authentication on your Neo4j DB.

Cheers
