### ISSUE TITLE
There is no procedure with the name `semantics.importRDF` registered for this database instance. Please ensure you’ve spelled the procedure name correctly and that the procedure is properly deployed.

### ISSUE THREAD

**Issue by pzerva** [jbarrasa/neosemantics#6]
Hi Jesus,

I am trying to use your translator but getting the same problems with Timo above
‘There is no procedure with the name `semantics.importRDF` registered for this database instance. Please ensure you’ve spelled the procedure name correctly and that the procedure is properly deployed.’

The steps I followed are below:
1. Downloaded source code
2. Generated the corresponding jar files with ‘mvn package’
3. Added the generated jars according to pom file in the plugin folder of Neo4J
on the plugins file in the C:/Program Files/Neon4J.. /plugins folder
4. Called the procedure over the web interface on Firefox browser
''CALL semantics.importRDF("http://fr.openfoodfacts.org/data/fr.openfoodfacts.org.products.rdf","RDF/XML",false,5000)''

I am thinking whether there might be jars missing as some of them were not downloaded with the mvn package according to the pom descriprion so I had to manually download these. This is the list of jars copied down to my Neon plugins folder.

neosemantics-1.0-SNAPSHOT.rar
junit-4.11.jar
sesame-rio-turtle-4.1.1
sesame-rio-ntriples-4.1.1.jar.jar
sesame-rio-trig-4.1.1.jar
sesame-rio-rdfxml-4.1.1.jar
sesame-rio-jsonld-4.1.1.jar
neo4j-3.0.1.jar
apoc-1.0.0.jar

Anything you could think of I may be doing wrong in the procedure?

Many thanks,
Veta

**Comment by jbarrasa** [comment]
It seems that the following jars are missing from your list:
sesame-model-4.1.1.jar 
sesame-rio-datatypes-4.1.1.jar
sesame-rio-languages-4.1.1.jar
are missing from your list?

Also I've accepted a PR from samuraraujo that produces a single jar bundling all dependencies.
However if you prefer the old way, it also produces the simple one that has to be accompanied by all the third party ones. 

I've checked in a good chunk of code, I'd recommend you pull the changes and retry.

Cheers,

JB.

**Comment by wadael** [comment]
There is a step 3.5

CREATE INDEX ON :Resource(uri) 
CREATE INDEX ON :URI(uri)
CREATE INDEX ON :BNode(uri) 
CREATE INDEX ON :Class(uri)

Step 4 now have a new parameter 
CALL semantics.importRDF("http://fr.openfoodfacts.org/data/fr.openfoodfacts.org.products.rdf","RDF/XML",false,true,5000)

Unfortunately, the import fails because of a character  [line 134210, column 850]

**Comment by pzerva** [comment]
Ok thanks a lot :-) I managed to make this work !
