### ISSUE TITLE
GET works fine; POST stopped working

### ISSUE THREAD

**Issue by BrainAnnex** [jbarrasa/neosemantics#61]
Hello, my installation consists of:

> * Neo4j Community Edition 3.4.9
> * Neosemantics Release 3.4.0.2 for Neo4j 3.4.x
> * APOC 3.4.0.2
> * (On Windows 10)

In my database, I have a Neo4j  node with ID 721380

If, within the browser interface, I issue:

> :GET /rdf/describe/id?nodeid=721380

all good.  It gives me a semantic description of that node.

BUT if I issue:

> :POST /rdf/cypher "MATCH (n) WHERE id(n)=721380 RETURN n"

then it gives me an error message:

> FetchURLError
> FetchURLError: Could not fetch URL: "500 Server Error". This could be due to the remote server policy. See your web browsers error console for more information.

and the Windows Power Shell that I used to start Neo4j says:

> 2018-11-02 07:21:57.275+0000 WARN  /rdf/cypher org.codehaus.jackson.map.JsonMappingException: Can not instantiate value of type [map type; class java.util.LinkedHashMap, [simple type, class java.lang.String] -> [simple type, class java.lang.String]] from JSON String; no single-String constructor/factory method

Even stranger is that fact that the POST method was working recently, on a previous version of Neo4j and of the Neosemantics plugin (as we discussed in a [separate thread](https://github.com/jbarrasa/neosemantics/issues/57)

![post error](https://user-images.githubusercontent.com/41893046/47899915-490e2a00-de38-11e8-9b11-7d42701792a1.JPG)
![capture power shell output](https://user-images.githubusercontent.com/41893046/47899917-49a6c080-de38-11e8-9b68-185bbdbfac67.JPG)

**Comment by BrainAnnex** [comment]
Eureka, I just realized that you **changed the syntax** of the POST calls from a couple of weeks ago!  I  double-checked the documentation, and discovered that one now needs curly braces and `"cypher":` around the quoted Cypher query.

When I re-state my earlier command (from within the browser interface) as:

> :POST /rdf/cypher {"cypher" : "MATCH (n) WHERE id(n)=721380 RETURN n"}

it now works fine :)  I hope this helps others, too...

----

On a side note, I notice a couple of puzzling things:

1) The **GET** is returning the node _AND the edges_, while the **POST** is returning just the node.  Is there a reason for that?

![post vs get](https://user-images.githubusercontent.com/41893046/47904250-1d903d00-de42-11e8-9fcf-97a079b97495.JPG)

2) Whereas I used to get JSON-LD by default, I'm now getting **Turtle**.  I'm actually happy with Turtle, but if I wanted to switch, is there a way to do that?

Thanks!

**Comment by jbarrasa** [comment]
Hi again BrainAnnex and thanks for using neosemantics. 

Yes, I changed the way parameters are passed to POST request to enable passing multiple parameters in a clean way. Sorry if I did not make it clear enough. Maybe I should have added it to the release notes (lesson learnt for future).

Regarding your second question, the `describe` method (GET) takes only the id of a node and returns all properties and relationships (incoming and outgoing) for it. It simulates the [DESCRIBE query form in SPARQL](https://www.w3.org/TR/rdf-sparql-query/#describe). 
The `cypher` method (POST) on the other hand, gives you full control on what is returned. If your cypher query -like the one in your case- returns only the nodes (notice the `RETURN n` in your query) , that's what will be serialised in RDF, but you should be able to return what you wish by changing your cypher. 

Let me give you an example, if you use a query like this: ` MATCH (n)-[r]->(m) WHERE n.ISBN = 'xyz' RETURN n,r,m` you'll get the selected node details plus all the outgoing relationships AND the details of the nodes linked through these relationships.

I hope this clarifies the differences between the two methods.

Cheesr,

JB.
