### ISSUE TITLE
Any way to upload named graphs?

### ISSUE THREAD

**Issue by jmugan** [jbarrasa/neosemantics#63]
I have data TriG format (4-tuples). Can anyone advise on the best way to get this data in Neo4j? Can neosemantics do reification?

**Comment by jbarrasa** [comment]
There’s no support for named graphs in the current version of Neo4j, so neosemantics just loads triples in a single graph. 

I would expect the rdf4j parser will parse your 4-tuples normally but neosemantics will ignore named graphs and load all into a single graph. Have you tried it?

Regarding reification, keep in mind that neosemantics will import the triples following the rules described here: https://jbarrasa.com/2016/06/07/importing-rdf-data-into-neo4j/. So depending on the type of reification you might need to do some post-processing on the imported graph.

Can you share your dataset (or maybe a sample)?

**Comment by jmugan** [comment]
Thanks for your response. I did try it; it errors with the 4-tuples.

The data comes from Pikes. For example, here is one of the tuples it generates
```
<fact:MfktDGRyRJyMNP483QDDX4> {
	<http://pikes.fbk.eu/#dog> a sumo:Carnivore .
}
```
All of the tuples for the sentence "The dog is red." can be found here https://gist.github.com/jmugan/735b4c83d0503796e6acec923e513ebe 

Here's a another example in 4-tuple form (the kind I tried to load into nosesemantics), it looks like this
```
<http://my_domain/opinion_99/#said> <http://www.newsreader-project.eu/ontologies/propbank/said.01_0> <http://my_domain/opinion_99/#she_5> <fact:FmggESjv9z3GDOYunfjEfG> .
```
which would come from a statement like "She said the dog is red." It would be good to be able to point to all of the things a person said. Do you know the best way to do that in Neo4j?

Thanks for your nice work on nosesemantics and your quality blog posts.

**Comment by jmugan** [comment]
Oh, nice, I didn't know "TriG" was an option for the procedure, so I had it as 'Turtle'. Thanks!
