### ISSUE TITLE
Invalid IRI

### ISSUE THREAD

**Issue by NJ2046** [jbarrasa/neosemantics#70]
**cmd: CALL semantics.importRDF('file:////home/user/dsc.nlp-bigdatalab.org.ttl','Turtle',{ shortenUrls: false, typesToLabels: true, commitSize: 9000} )

extraInfo_case0: Invalid IRI 'http://dsc.nlp-bigdatalab.org:8086/免疫球蛋白E]冷球蛋白试验 [line 1141]
to_do: del [
question: can ignore ?

extraInfo_case1:"IRI included an unencoded space: '32' [line 2421]"

to_do: ?**

neo4j_log
2019-03-21 11:58:16.167+0000 INFO  Found 7 namespaces in the DB: {http://purl.org/dc/elements/1.1/=dc, http://www.w3.org/1999     /02/22-rdf-syntax-ns#=rdf, http://purl.org/dc/terms/=dct, http://www.w3.org/2002/07/owl#=owl, http://www.w3.org/2004/02/skos/     core#=skos, http://schema.org/=sch, http://www.w3.org/2000/01/rdf-schema#=rdfs}
2467 org.eclipse.rdf4j.rio.RDFParseException: Invalid IRI 'http://dsc.nlp-bigdatalab.org:8086/免疫球蛋白E]冷球蛋白试验 [line 1141]
2468     at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportError(RDFParserHelper.java:322)
2469     at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportError(AbstractRDFParser.java:673)
2470     at org.eclipse.rdf4j.rio.turtle.TurtleParser.reportError(TurtleParser.java:1309)
2471     at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.resolveURI(AbstractRDFParser.java:387)
2472     at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseURI(TurtleParser.java:941)
2473     at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseValue(TurtleParser.java:588)
2474     at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseSubject(TurtleParser.java:429)
2475     at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseTriples(TurtleParser.java:370)
2476     at org.eclipse.rdf4j.rio.turtle.TurtleParser.parseStatement(TurtleParser.java:239)
2477     at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:201)
2478     at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:143)
2479     at semantics.RDFImport.importRDF(RDFImport.java:74)
2480     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2481     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2482     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2483     at java.lang.reflect.Method.invoke(Method.java:498)
2484     at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler$ReflectiveProcedure.apply(ReflectiveProcedureCompiler.java:648)
2485     at org.neo4j.kernel.impl.proc.ProcedureRegistry.callProcedure(ProcedureRegistry.java:219)
2486     at org.neo4j.kernel.impl.proc.Procedures.callProcedure(Procedures.java:290)
2487     at org.neo4j.kernel.impl.newapi.AllStoreHolder.callProcedure(AllStoreHolder.java:1072)
2488     at org.neo4j.kernel.impl.newapi.AllStoreHolder.procedureCallWrite(AllStoreHolder.java:852)
2489     at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$$anonfun$6.apply(TransactionBoundQueryConte     xt.scala:874)
2490     at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext$$anonfun$6.apply(TransactionBoundQueryConte     xt.scala:874)
2491     at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext.callProcedure(TransactionBoundQueryContext.     scala:937)
2492     at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext.callReadWriteProcedure(TransactionBoundQuer     yContext.scala:875)
2493     at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext$$anonfun$callReadWriteProcedure$1.apply(     ExceptionTranslatingQueryContext.scala:149)
2494     at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext$$anonfun$callReadWriteProcedure$1.apply(     ExceptionTranslatingQueryContext.scala:149)
2495     at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslationSupport$class.translateException(ExceptionTranslation     Support.scala:33)
2496     at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQ     ueryContext.scala:41)
2497     at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslationSupport$class.translateIterator(ExceptionTranslationS     upport.scala:47)
2498     at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext.translateIterator(ExceptionTranslatingQu     eryContext.scala:41)
2499     at org.neo4j.cypher.internal.compatibility.v3_4.ExceptionTranslatingQueryContext.callReadWriteProcedure(ExceptionTranslat     ingQueryContext.scala:149)
2500     at org.neo4j.cypher.internal.runtime.EagerReadWriteCallMode.callProcedure(ProcedureCallMode.scala:64)
2501     at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.procs.ProcedureExecutionResult.executeCall(Procedur     eExecutionResult.scala:73)
2502     at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.procs.ProcedureExecutionResult.<init>(ProcedureExec     utionResult.scala:69)
2503     at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.procs.ProcedureCallExecutionPlan.createNormalExecut     ionResult(ProcedureCallExecutionPlan.scala:90)
2504     at org.neo4j.cypher.internal.compatibility.v3_4.runtime.executionplan.procs.ProcedureCallExecutionPlan.run(ProcedureCallE     xecutionPlan.scala:80)
2505     at org.neo4j.cypher.internal.compatibility.LatestRuntimeVariablePlannerCompatibility$ExecutionPlanWrapper$$anonfun$run$1.     apply(LatestRuntimeVariablePlannerCompatibility.scala:128)
2506     at org.neo4j.cypher.internal.compatibility.LatestRuntimeVariablePlannerCompatibility$ExecutionPlanWrapper$$anonfun$run$1.     apply(LatestRuntimeVariablePlannerCompatibility.scala:124)
2507     at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
2508     at org.neo4j.cypher.internal.compatibility.LatestRuntimeVariablePlannerCompatibility$ExecutionPlanWrapper.run(LatestRunti     meVariablePlannerCompatibility.scala:124)
2509     at org.neo4j.cypher.internal.PreparedPlanExecution.execute(PreparedPlanExecution.scala:29)
2510     at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:119)
2511     at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:61)
2512     at org.neo4j.bolt.v1.runtime.TransactionStateMachineSPI$1.start(TransactionStateMachineSPI.java:144)
2513     at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.startExecution(TransactionStateMachine.java:444)
2514     at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.execute(TransactionStateMachine.java:259)
2515     at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.run(TransactionStateMachine.java:240)
2516     at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:81)
2517     at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$2.run(BoltStateMachine.java:457)
2518     at org.neo4j.bolt.v1.runtime.BoltStateMachine.run(BoltStateMachine.java:225)
2519     at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onRun$3(BoltMessageRouter.java:93)
2520     at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.lambda$enqueue$0(MetricsReportingBoltConnection.java:69)
2521     at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:195)
2522     at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.processNextBatch(MetricsReportingBoltConnection.java:87)
2523     at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:143)
2524     at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:170)
2525     at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:153)
2526     at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
2527     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2528     at java.util.concurrent.ThreadPoolExecu

**Comment by jbarrasa** [comment]
It seems the RDF parser is throwing an exception on an invalid IRI.
It's an RDF parser issue, not neosemantics code. Maybe worth having a look at [the RDF4J documentation.](http://docs.rdf4j.org/programming/#_parsing_and_writing_rdf_with_rio)
Are you sure the RDF is well-formed? Is it possible that somehow some invalid characters are being introduced in the IRIs?
LMK

**Comment by NJ2046** [comment]
thanks.
RDF's format is error.
I fixed format.
so run ok.

**Comment by jbarrasa** [comment]
great, thanks for the update.
