### ISSUE TITLE
liteOntoImport fails to build :SPO relation

### ISSUE THREAD

**Issue by mdw00d** [jbarrasa/neosemantics#72]
This seems to be the same issue as #59 except for :SPO.   Attached are two OWL files.   In the first (SPOTest) the definition of the super property appears last.  In this case, when the file is imported, the :SPO relationship/edges are not created.   However, if the definition of the super property is moved within file to appear before the definition of the sub properties, the :SPO relationships are created as expected.

[SPOTest.zip](https://github.com/jbarrasa/neosemantics/files/3018147/SPOTest.zip)

**Comment by mdw00d** [comment]
Here's a simple fix; the issue is that the node corresponding to the super property may not have been created:


diff --git a/src/main/java/semantics/LiteOntologyImporter.java b/src/main/java/semantics/LiteOntologyImporter.java
index fd47021..6357cbb 100644
--- a/src/main/java/semantics/LiteOntologyImporter.java
+++ b/src/main/java/semantics/LiteOntologyImporter.java
@@ -91,9 +91,17 @@ public class LiteOntologyImporter {
                 db.execute(cypher, params);
                 propsLoaded++;
                 extractDomainAndRange(model, propResource, propType);
+                // Need to wait until everybody has been created before doing this
+                // extractPropertyHierarchy(model, propResource, propType);
+            }
+        }
+
+        for ( Resource propResource : allDatatypeProps) {
+            if (!(propResource instanceof BNode)) {
                 extractPropertyHierarchy(model, propResource, propType);
             }
         }
+
         return propsLoaded;
     }

**Comment by mdw00d** [comment]
Here's a simple fix; the issue is that the node representing the super property may not have been created yet:
```
diff --git a/src/main/java/semantics/LiteOntologyImporter.java b/src/main/java/semantics/LiteOntologyImporter.java
index fd47021..6357cbb 100644
--- a/src/main/java/semantics/LiteOntologyImporter.java
+++ b/src/main/java/semantics/LiteOntologyImporter.java
@@ -91,9 +91,17 @@ public class LiteOntologyImporter {
                 db.execute(cypher, params);
                 propsLoaded++;
                 extractDomainAndRange(model, propResource, propType);
+                // Need to wait until everybody has been created before doing this
+                // extractPropertyHierarchy(model, propResource, propType);
+            }
+        }
+
+        for ( Resource propResource : allDatatypeProps) {
+            if (!(propResource instanceof BNode)) {
                 extractPropertyHierarchy(model, propResource, propType);
             }
         }
+
         return propsLoaded;
     }
```

**Comment by jbarrasa** [comment]
Hi mdw00d, thanks!
I actually merged a pull request solving that problem in a very similar way.
Should be included in next release.
I guess you have your fix, but you could also build from source.

Cheers,

JB.

**Comment by mdw00d** [comment]
Thanks for the reply.  I see the commit that fixed this issue for classes, but I don't see the corresponding fix for properties?

**Comment by jbarrasa** [comment]
Oh! I missed that. Fixed now.
Thank you very much.
