### ISSUE TITLE
Getting the URI of a property

### ISSUE THREAD

**Issue by noorbakerally** [jbarrasa/neosemantics#75]
I am trying to get the URI of a property with the following query but it returns only `null`

**Query:**
`MATCH (n:Resource {uri:'http://elite.polito.it/ontologies/dogont.owl#Actuator'})-[r]->() Return r.uri`

**Result**
╒═══════╕
│"r.uri"│
╞═══════╡
│null   │
├───────┤
│null   │
└───────┘

The plugin, does it not save the URI of the predicate ?

**Comment by jbarrasa** [comment]
Hi @noorbakerally.
You can try this:
`MATCH (n:Resource {uri:'http://elite.polito.it/ontologies/dogont.owl#Actuator'})-[r]->() Return type(r)`

The uri of the relationship is not stored as a property but as it's type. You can find out more about [the way RDF is mapped to LPG here](https://jbarrasa.com/2016/06/07/importing-rdf-data-into-neo4j/) (see rule  2b).

I hope this helps.

JB.
