### ISSUE TITLE
CALL semantics.importRDF "Invalid IRI 'http://pkupiekb.org/resource/草莓100% [line 23880]"

### ISSUE THREAD

**Issue by zailushang2006** [jbarrasa/neosemantics#76]
I want to import the Turtle file into neo4j,  running the CALL semantics.importRDF, 
error is "Invalid IRI 'http://pkupiekb.org/resource/草莓100% [line 23880]"
I guess is because the “%” in URI does not have Percent-encoding. But this "%" has a special meaning in the entity and cannot be replaced by "%". How can I solve it?

**Comment by manonthegithub** [comment]
You should encode your non-ascii symbols in the url encoding 
`草莓100% => %E8%8D%89%E8%8E%93100%25`
[here](https://meyerweb.com/eric/tools/dencoder/) is the link to online url encoder-decoder

**Comment by manonthegithub** [comment]
PR I created can solve this issue for you.

**Comment by jbarrasa** [comment]
Fix merged, so issue should be fixed by now.
Please reopen if not.
