### ISSUE TITLE
What should i do after i import owl file?

### ISSUE THREAD

**Issue by SinTaken** [jbarrasa/neosemantics#77]
First i use protege to built a owl file,and then i import this file into neo4j,it was successful.
But i got a question :it didn't show the graph,only told me triplesloaded 360.(no graph choice there)
How can i work it out to get the graph?

**Comment by jbarrasa** [comment]
Well, neo4j is a DB so once your ontology is loaded you can query it.
If all you want is a graph view of the imported ontology you can do this:
`MATCH (n)-[r]-() RETURN n, r`
[Here](https://neo4j.com/docs/cypher-refcard/current/)'s a link to the cypher reference for all the cool things you can do with your data.

What was the purpose of loading your ontology into neo4j?

Thanks!

JB

**Comment by jbarrasa** [comment]
You can also get some ideas from [the manual](http://jbarrasa.github.io/neosemantics/).
