### ISSUE TITLE
Compile error in LiteOntologyImporter

### ISSUE THREAD

**Issue by gitsharp** [jbarrasa/neosemantics#8]
Hi,

I get a compile error on line 161 of "public class LiteOntologyImporter" .
Error:
(The method getName() is undefined for the type RDFFormat)
the line in question:
 if (parser.getName().equals(format))
I havent had time to look into this....

kind regards,
Black

**Comment by jbarrasa** [comment]
I cannot reproduce this behavior, gitsharp :(
Can you provide more details? 
Also, have you pulled the last commited changes?
Cheers,

JB.

**Comment by gitsharp** [comment]
Hi Jesús Barrasa,

Thanks for the code.. I was wasn't building with maven but in eclipse by hand. I missed a few libraries it seems. I have noticed though that in the pom.xml you did not specify "aduna-commons-lang-2.2.jar" and a few more from sesame.rio was needed to compile.

kind regards, Black

**Comment by gitsharp** [comment]
Hi Jesús,

Thanks, It works now. I had installed a neo instance on a Linux system. In windows the plugins were just not detected....

kind regards, Black

**Comment by jbarrasa** [comment]
Great stuff, Black. 
I'll close the issue then.
Cheers,

JB.
