### ISSUE TITLE
"a" relation not imported

### ISSUE THREAD

**Issue by jvanulde** [jbarrasa/neosemantics#82]
I imported the following resource: 

    https://geoconnex.ca/gsip/info/catchment/02OJ*CB?f=ttl

The relation between `http://geosciences.ca/def/hydraulic#HY_Catchment` and `https://geoconnex.ca/id/catchment/02OJ*CB` is not realized in the resulting graph.

**Comment by jbarrasa** [comment]
Hi @jvanulde, when you run a basic import like this:
```
call semantics.importRDF("https://geoconnex.ca/gsip/info/catchment/02OJ*CB?f=ttl","Turtle")
```
The `rdf:type` relationships are by default translated into Labels in Neo4j. Essentially, if you have a triple like `x rdf:type y` , you'll get a node representing `x` with a label `y`.
So in your example you'll see that if you run the following cypher query, you'll get all the types for your resource, including the`http://geosciences.ca/def/hydraulic#HY_Catchment` :

```
MATCH (r:Resource { uri: "https://geoconnex.ca/id/catchment/02OJ*CB"})
RETURN [ x in labels(r) | semantics.uriFromShort(x) ] as alltypes

╒══════════════════════════════════════════════════════════════════════╕
│"alltypes"                                                            │
╞══════════════════════════════════════════════════════════════════════╡
│["Resource","http://www.w3.org/2002/07/owl#Thing","http://www.w3.org/2│
│000/01/rdf-schema#Resource","http://geosciences.ca/def/hydraulic#HY_Ca│
│tchment"]                                                             │
└──────────────────────────────────────────────────────────────────────┘
```
Now if you want neosemantics to keep the `rdf:types` as separate nodes, all you need to do is add this extra parameter:

```
call semantics.importRDF("https://geoconnex.ca/gsip/info/catchment/02OJ*CB?f=ttl","Turtle", { typesToLabels: false })
```
You should immediately see the resource is now connected to multiple nodes, one per `rdf:type`.
The query you need to run in this case is slightly different:

```
MATCH (:Resource { uri: "https://geoconnex.ca/id/catchment/02OJ*CB" } )-[r:rdf__type]->(type) 
RETURN collect(type.uri) as alltypes

╒══════════════════════════════════════════════════════════════════════╕
│"allTypes"                                                            │
╞══════════════════════════════════════════════════════════════════════╡
│["http://www.w3.org/2002/07/owl#Thing","http://www.w3.org/2000/01/rdf-│
│schema#Resource","http://geosciences.ca/def/hydraulic#HY_Catchment"]  │
└──────────────────────────────────────────────────────────────────────┘
```

I hope this helps. It will all be covered in the manual pages that I hope I'll publish in the next few days.

Cheers,

JB.

**Comment by jbarrasa** [comment]
I'll take silence as an 'ok' and close the issue hoping that the examples clarified the behavior. 

Please reopen if needed.
