### ISSUE TITLE
Small bug with counting number of imported triples

### ISSUE THREAD

**Issue by manonthegithub** [jbarrasa/neosemantics#87]
While importing the number of imported triples is logged:
`2019-06-07 04:59:18.626+0000 INFO  Successful partial commit of 100000 triples. 1804432704 triples ingested so far...`

We are importing billions (18) of triples and it overflowed the Integer. At some point we got negative values for triples and a bit later positive starting with 0 again :). A small fix changing the counter to Long should work.

**Comment by jbarrasa** [comment]
Thanks for the heads up. Fixed and also reduced the verbosity of the logging.
