### ISSUE TITLE
Problem with :GET. unable to expose data as rdf

### ISSUE THREAD

**Issue by shwetank2174** [jbarrasa/neosemantics#98]
I am using Neo4j desktop version 3.5.
I have installed the Neosemantics plugin and :GET /rdf/ping works fine.
I loaded the moviegraph and I am trying to expose the data as RDF using
" :GET /semantic/describe/id?nodeid=60".
When I check the node is existing. But I am unable to get the information in RDF. 
The following error pops up:
![image](https://user-images.githubusercontent.com/40026590/60765088-11840b80-a0b2-11e9-995d-6f7d9f13176d.png)

Thanks.

**Comment by jbarrasa** [comment]
Hi @shwetank2174 , based on the neo4j.conf file you shared [here](https://github.com/jbarrasa/neosemantics/issues/94#issuecomment-508693634), it looks like you mounted the extension on `/rdf` so you'd need to call the `describe` method on the same URL. Something like:

`:GET /rdf/describe/id?nodeid=60`

Also, notice that I've pushed some changes that slightly change the structure of the URL, so in the next release (hopefully in the next few days) the `describe` endpoint would look like this instead:

`:GET /rdf/describe/id/60`

I'll publish documentation and examples with it.

Hope this helps.

JB.

**Comment by shwetank2174** [comment]
Thanks.
That resolves the issue.
